version: '3'
services:
  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - ./fauxhaus:/var/lib/clickhouse/user_scripts/fauxhaus
      - ./fauxhaus_function.xml:/etc/clickhouse-server/fauxhaus_function.xml
    restart: always

